apiVersion: v1
kind: Service
metadata:
  name: queue2-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: queue2
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  type: ClusterIP